apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-petclinic-deployment
  name: springboot-petclinic
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-petclinic
  template:
    metadata:
      labels:
        app: springboot-petclinic
    spec:
      containers:
      - name: my-springboot-petclinic
        image: public.ecr.aws/n8u2g7a5/my-first-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-petclinic
    k8s-app: springboot-petclinic
  name: springboot-petclinic
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-petclinic
